#
#  ██████╗ ███████╗██╗   ██╗ ██████╗ ██╗  ██╗███████╗███╗   ██╗
#  ██╔══██╗██╔════╝██║   ██║██╔═══██╗██║ ██╔╝██╔════╝████╗  ██║
#  ██████╔╝█████╗  ██║   ██║██║   ██║█████╔╝ █████╗  ██╔██╗ ██║
#  ██╔══██╗██╔══╝  ╚██╗ ██╔╝██║   ██║██╔═██╗ ██╔══╝  ██║╚██╗██║
#  ██║  ██║███████╗ ╚████╔╝ ╚██████╔╝██║  ██╗███████╗██║ ╚████║
#  ╚═╝  ╚═╝╚══════╝  ╚═══╝   ╚═════╝ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝
#
# "ANSI Shadow" from http://patorjk.com/software/taag/
# Version:    ${version}
# Build time: ${timestamp}
# --
# Chat configuration
#
chat:
  # Disable messages that only contain colors and appear blank
  disable-blank-messages: true
  emoticons:
    # Default permission for emoticons
    permission: ""
    enabled: true
    # Indicates that emote key is following
    indicator: "\\"
    emotes:
      why:
        key: "why"
        emote: "( •_•)"
      ohyeah:
        key: "ohyeah"
        emote: "(￢‿￢ )"
      yaay:
        key: "yaay"
        emote: "＼(￣▽￣)／"
      blush:
        key: "blush"
        emote: "(≧ω≦)"
      hiii:
        # Override indicator
        indicator: ""
        key: "o/"
        emote: "( ﾟ◡ﾟ)/"
      overlord:
        key: "overlord"
        emote: "&f&kEEE &eOverlord &f&kEEE"
        permission: "regna.admin"
      whytho:
        key: "whytho"
        emote: "(＞﹏＜)"
      sus:
        key: "sus"
        emote: "( ͡─ ͜ʖ ͡─)"
      idc:
        key: "idc"
        emote: "¯\\_(ツ)_/¯"
      hi:
        key: "hi"
        emote: "\\(•◡•)/"
      gib:
        key: "gib"
        emote: "༼つ◕_◕༽つ"
      smirk:
        key: "smirk"
        emote: "(¬‿¬)"
      stare:
        key: "stare"
        emote: "ಠ ᴗ ಠ"
      kiss:
        key: "kiss"
        emote: "(づ￣ ³￣)づ"
      what:
        key: "what"
        emote: "⚆ _ ⚆"
      kyticka:
        key: "kyticka"
        emote: "(◕‿◕✿)"
      joy:
        key: "joy"
        emote: "＼(^o^)／"
      srsly:
        key: "srsly"
        emote: "(ㆆ_ㆆ)"
      bear:
        key: "bear"
        emote: "ʕ•ᴥ•ʔ"
      whatwhy:
        key: "whatwhy"
        emote: "◉_◉"
  mention:
    permission: ""
    enabled: true
    indicator: ""
    color: "&o"
    sound:
      name: "BLOCK_BELL_USE"
      volume: 1
      pitch: 1
  permission-color: { }

