#
#  ██████╗ ███████╗██╗   ██╗ ██████╗ ██╗  ██╗███████╗███╗   ██╗
#  ██╔══██╗██╔════╝██║   ██║██╔═══██╗██║ ██╔╝██╔════╝████╗  ██║
#  ██████╔╝█████╗  ██║   ██║██║   ██║█████╔╝ █████╗  ██╔██╗ ██║
#  ██╔══██╗██╔══╝  ╚██╗ ██╔╝██║   ██║██╔═██╗ ██╔══╝  ██║╚██╗██║
#  ██║  ██║███████╗ ╚████╔╝ ╚██████╔╝██║  ██╗███████╗██║ ╚████║
#  ╚═╝  ╚═╝╚══════╝  ╚═══╝   ╚═════╝ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝
#
# "ANSI Shadow" from http://patorjk.com/software/taag/
# Version:    ${version}
# Build time: ${timestamp}
# --
# Interface configuration
#
first-join-title:
  enabled: true
  title: "<GRADIENT:ff5900>Vitaj</GRADIENT:ffe700> &7%player_name% <GRADIENT:ff5900>na BattleLand.eu</GRADIENT:ffe700> "
  subtitle: ""
  times:
    fade-in: 10
    stay: 30
    fade-out: 10
join-title:
  enabled: false
  title: "aaaaaaaaaaaahoj pica"
  subtitle: ""
  times:
    fade-in: 10
    stay: 30
    fade-out: 10
