#
#  ██████╗ ███████╗██╗   ██╗ ██████╗ ██╗  ██╗███████╗███╗   ██╗
#  ██╔══██╗██╔════╝██║   ██║██╔═══██╗██║ ██╔╝██╔════╝████╗  ██║
#  ██████╔╝█████╗  ██║   ██║██║   ██║█████╔╝ █████╗  ██╔██╗ ██║
#  ██╔══██╗██╔══╝  ╚██╗ ██╔╝██║   ██║██╔═██╗ ██╔══╝  ██║╚██╗██║
#  ██║  ██║███████╗ ╚████╔╝ ╚██████╔╝██║  ██╗███████╗██║ ╚████║
#  ╚═╝  ╚═╝╚══════╝  ╚═══╝   ╚═════╝ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝
#
# "ANSI Shadow" from http://patorjk.com/software/taag/
# Version:    ${version}
# Build time: ${timestamp}
# --
# Chat configuration
#
chat:
  # Disable messages that only contain colors and appear blank
  disable-blank-messages: true
  emoticons:
    # Default permission for emoticons
    permission: ""
    enabled: true
    # Indicates that emote key is following
    indicator: "\\"
    emotes:
      what:
        key: "what"
        emote: "( •_•)"
      ohyeah:
        key: "ohyeah"
        emote: "(￢‿￢ )"
      yaay:
        key: "yaay"
        emote: "＼(￣▽￣)／"
      blush:
        key: "blush"
        emote: "(≧ω≦)"
      hiii:
        # Override indicator
        indicator: ""
        key: "o/"
        emote: "( ﾟ◡ﾟ)/"
      overlord:
        key: "overlord"
        emote: "&f&kEEE &eOverlord &f&kEEE"
        permission: "regna.admin"
  mention:
    permission: ""
    enabled: true
    indicator: ""
    color: "&e"
    color-based-on-chatcolor: true
    sound:
      name: "BLOCK_BELL_USE"
      volume: 1
      pitch: 1
    messages:
      somebody-mentioned-you: ""
  permission-color: {}
