#
#  ██████╗ ███████╗██╗   ██╗ ██████╗ ██╗  ██╗███████╗███╗   ██╗
#  ██╔══██╗██╔════╝██║   ██║██╔═══██╗██║ ██╔╝██╔════╝████╗  ██║
#  ██████╔╝█████╗  ██║   ██║██║   ██║█████╔╝ █████╗  ██╔██╗ ██║
#  ██╔══██╗██╔══╝  ╚██╗ ██╔╝██║   ██║██╔═██╗ ██╔══╝  ██║╚██╗██║
#  ██║  ██║███████╗ ╚████╔╝ ╚██████╔╝██║  ██╗███████╗██║ ╚████║
#  ╚═╝  ╚═╝╚══════╝  ╚═══╝   ╚═════╝ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝
#
# "ANSI Shadow" from http://patorjk.com/software/taag/
# Version:    ${version}
# Build time: ${timestamp}
# --
# SilkSpawners Configuration
#


spawners:
  required-tools:
    - "iron_pickaxe"
    - "diamond_pickaxe"
    - "netherite_pickaxe"
  required-enchantments:
    - "silk_touch"
  item:
    name: "§fSpawner §e{entity}"
    lore: "§7Durabilita §r{durability}"
  durability: 3
  show-durability: true
durability-progress-bar:
  step-min: 0
  step-max: 3
  visual:
    border: "§8┃"
    completed-step: "§a░"
    uncompleted-step: "§7░"
