#
#  ██████╗ ███████╗██╗   ██╗ ██████╗ ██╗  ██╗███████╗███╗   ██╗
#  ██╔══██╗██╔════╝██║   ██║██╔═══██╗██║ ██╔╝██╔════╝████╗  ██║
#  ██████╔╝█████╗  ██║   ██║██║   ██║█████╔╝ █████╗  ██╔██╗ ██║
#  ██╔══██╗██╔══╝  ╚██╗ ██╔╝██║   ██║██╔═██╗ ██╔══╝  ██║╚██╗██║
#  ██║  ██║███████╗ ╚████╔╝ ╚██████╔╝██║  ██╗███████╗██║ ╚████║
#  ╚═╝  ╚═╝╚══════╝  ╚═══╝   ╚═════╝ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝
#
# "ANSI Shadow" from http://patorjk.com/software/taag/
# Version:    ${version}
# Build time: ${timestamp}
# --
# Mechanics Configuration
#
