#
#  ██████╗ ███████╗██╗   ██╗ ██████╗ ██╗  ██╗███████╗███╗   ██╗
#  ██╔══██╗██╔════╝██║   ██║██╔═══██╗██║ ██╔╝██╔════╝████╗  ██║
#  ██████╔╝█████╗  ██║   ██║██║   ██║█████╔╝ █████╗  ██╔██╗ ██║
#  ██╔══██╗██╔══╝  ╚██╗ ██╔╝██║   ██║██╔═██╗ ██╔══╝  ██║╚██╗██║
#  ██║  ██║███████╗ ╚████╔╝ ╚██████╔╝██║  ██╗███████╗██║ ╚████║
#  ╚═╝  ╚═╝╚══════╝  ╚═══╝   ╚═════╝ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝
#
# "ANSI Shadow" from http://patorjk.com/software/taag/
# Version:    ${version}
# Build time: ${timestamp}
# --
# Vote configuration
#
vote-reminder:
  enabled: true
  vote-again-czechcraft:
    - " "
    - "<click:run_command:/vote>&e&lVote &8● &fKlikni sem a poď znova zahlasovať!</click>"
    - " "
  vote-again-craftlist:
    - " "
    - "<click:run_command:/vote>&e&lVote &8● &fKlikni sem a poď znova zahlasovať!</click>"
    - " "
  # In seconds
  update-time: 300
  remind-count: 3
